platform :ios, '7.0'
pod 'XMPPFramework/Core', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/Reconnect', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/XEP-0045', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/Roster', :podspec => 'xmpp.podspec'
#Development
pod 'MobilisMXi', :path => '/Users/martin/Development/Mobilis/Mobilis'
#Final – used when the MXi is not under development locally
#pod 'MobilisMXi', :podspec => 'mxi.podspec'
